n = map(int, input("Введите размер первого массива: ").split())
m = map(int, input("Введите размер второго массива: ").split())
a = set(map(int, input("Введите элементы первого массива: ").split()))
b = set(map(int, input("Введите элементы второго массива: ").split()))
print(f"Уникальные числа: ", *sorted(a & b))